name: dev

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setting up java
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Caching dependencies
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test
        run: mvn test

      # Packaging
      - name: Build with Maven
        run: mvn clean compile assembly:single

      # Packaging workflow data as artifacts
      - run: mkdir artifact && cp target/*.jar artifact
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: artifact

      # Download artifact
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - run: |
          # docker build -t kafka-project-test . -f .github/Dockerfile
          ls artifact

